### PR TITLE
Fix bot not updating category of streamer

### LINKED ISSUE #60: Bot doesn't automatically update the category
image

image

### PR DESCRIPTION
**Pull request by TrojanerHD**
Fixes https://github.com/TrojanerHD/TrojanerBot/issues/60

The array that managed the messages was (why ever) previously empty. I assume it was forgotten in a (more or less) recent change.

### CODE REVIEW

File: src/twitch/DMManager.ts [hunk 1]
```diff
@@ -127,10 +147,14 @@ export default class DMManager {
...
       messageStream.game = streamer.game_name;
-      await messageStream.message
-        .edit(DMManager.generateMessage(streamer))
-        .catch(console.error);
+
+      const messageContent: MessageOptions & MessageEditOptions =
+        DMManager.generateMessage(streamer);
+
+      for (const message of messageStream.messages)
+        await message.edit(messageContent).catch(console.error);
```
Comment (TrojanerHD) [inline src/twitch/DMManager.ts]: Maybe rewrite this using Promise.all()?

**Comment by TrojanerHD** [comment]
Works as intended in my test environment :+1:
